#ifndef __OPENNI_INCLUDE_TYPES_HPP__
#define __OPENNI_INCLUDE_TYPES_HPP__

typedef unsigned int uint;

// EFFECTIVE DEPTH RANGE   [mm]
#define DEFAULT_DEPTH_MIN   800
#define DEFAULT_DEPTH_MAX 10000

// EDDECTIVE IR VALUE RANGE
#define DEFAULT_IR_MIN 0
#define DEFAULT_IR_MAX 1024

#endif
